export const POSTS_LOAD_PENDING = 'POSTS_LOAD_PENDING'
export const POSTS_LOAD_SUCCESS = 'POSTS_LOAD_SUCCESS'
export const POSTS_LOAD_FAILURE = 'POSTS_LOAD_FAILURE'
export const POST_LOAD_PENDING = 'POST_LOAD_PENDING'
export const POST_LOAD_SUCCESS = 'POST_LOAD_SUCCESS'
export const POST_LOAD_FAILURE = 'POST_LOAD_FAILURE'

export const SEARCH_CHANGE = 'SEARCH_CHANGE'
